#%RAML 0.8
title: supplier availability
baseUri: https://dropshipdemo.iqmetrix.net/v1
schemas: 

    
    - Availability: |
        {
          "name": "Availability",
          "type": "object",
          "$schema": "http://json-schema.org/draft-03/schema",
          "properties": {
            "Id": { "type": "GUID", "description": "Unique identifier", "example": "c2a97823-196b-4b3e-891a-ba01665797e4", "generated": "true" }, 
            "Products": { "type": "array", "arrayType": "object", "description": "Products for the Availability Feed", "isNested": "true", "ref": "supplier availability.ProductAvail" }
          },
          "required": [ "Products" ]
        }
        

    

    
    - ProductAvail: |
        {
          "exclude": "true",
          "name": "ProductAvail",
          "type": "object",
          "$schema": "http://json-schema.org/draft-03/schema",
          "properties": {
            "IsAvailable": { "type": "boolean", "description": "A flag to indicate if the Product is Available", "example": "true" },
            "Sku": { "type": "string", "description": "Vendor SKU", "example": "9101AGAP6" },
            "Quantity": { "type": "integer", "description":"Product quantity", "example": "10" }
          },
          "required": [ "Sku" ]
        }      
        

    

    
    - Product: |
        {
          "exclude": "true",
          "name": "Product",
          "type": "object",
          "$schema": "http://json-schema.org/draft-03/schema",
          "properties": {
            "IsAvailable": { "type": "boolean", "description": "A flag to indicate if the Product is Available", "example": "true" },
            "SupplierEntityId": { "type": "integer", "description": "Identifier for the Supplier of this Item", "ref": "entity-store.Supplier.Id" }, 
            "SupplierSku": { "type": "string", "description": "Vendor SKU", "example": "9101AGAP6" },
            "Quantity": { "type": "integer", "description": "Product quantity", "example": "10" }
          }
        }   
        

    


/Suppliers({SupplierId})/Availability:
    
    uriParameters:
        
        SupplierId:
            displayName: SupplierId
            type: integer
            example: 14107
            required: true
            description: Identifier for the <a href='http://developers.iqmetrix.com/api/entity-store/#supplier'>Supplier</a>
          
      
    post:
        
        displayName: Configuring Product Availability
                
        
        headers:
            
            Authorization:
                example: Bearer (Access Token)
            
            Accept:
                example: application/json
            
            Content-Type:
                example: application/json
            
        body:
            
            application/json:
                
                
                example: |  
                    
                    {"Products":[{"IsAvailable":true,"Sku":"9101AGAP6","Quantity":10}]}
                    
                schema: |
                    {"name":"Availability","type":"object","$schema":"http://json-schema.org/draft-03/schema","properties":{"Id":{"type":"GUID","description":"Unique identifier","example":"c2a97823-196b-4b3e-891a-ba01665797e4","generated":"true"},"Products":{"type":"array","arrayType":"object","description":"Products for the Availability Feed","isNested":"true","ref":"supplier availability.ProductAvail","properties":{"IsAvailable":{"type":"boolean","description":"A flag to indicate if the Product is Available","example":"true","name":"IsAvailable"},"Sku":{"type":"string","description":"Vendor SKU","example":"9101AGAP6","name":"Sku"},"Quantity":{"type":"integer","description":"Product quantity","example":"10","name":"Quantity"}},"required":["Sku"]}},"required":["Products"]}
                
            
        responses:
            
            202:
                
                body:
                    
                    application/json:
                        
                            
                            example: |
                                {"Id":"c2a97823-196b-4b3e-891a-ba01665797e4","Products":[{"IsAvailable":true,"Sku":"9101AGAP6","Quantity":10}]}
                            schema: |
                                {"name":"Availability","type":"object","$schema":"http://json-schema.org/draft-03/schema","properties":{"Id":{"type":"GUID","description":"Unique identifier","example":"c2a97823-196b-4b3e-891a-ba01665797e4","generated":"true"},"Products":{"type":"array","arrayType":"object","description":"Products for the Availability Feed","isNested":"true","ref":"supplier availability.ProductAvail","properties":{"IsAvailable":{"type":"boolean","description":"A flag to indicate if the Product is Available","example":"true","name":"IsAvailable"},"Sku":{"type":"string","description":"Vendor SKU","example":"9101AGAP6","name":"Sku"},"Quantity":{"type":"integer","description":"Product quantity","example":"10","name":"Quantity"}},"required":["Sku"]}},"required":["Products"]}
                            
                        
                    
                
            
    
