#%RAML 0.8
title: att-auth-proxy
version: v1
baseUri: https://authproxyatt.iqmetrix.net/v1
documentation:
  - title: overview
    content: |    
      Proxy for interacting with AT&T's CSP. 
resourceTypes:
    - singularEndpointReadOnly:
        get:
            headers:
              Authorization:
                example: Bearer (Access Token)
                description: See <a href='/api/authentication/#obtaining-an-access-token'>Obtaining an Access Token</a>                
              Accept:
                example: application/json     
            responses:
                200:
                    body:
                        application/json:
                          schema: <<resource>>
securitySchemes:
    - oauth_2_0:
        description: |
            iQmetrix APIs support OAuth 2.0 for authenticating API requests.
        type: OAuth 2.0
        describedBy:
            headers:
                Authorization:
                    description: |
                       Used to send a valid OAuth 2 access token.
                    type: string
            responses:
                401:
                    description: |
                        Bad or expired token. This can happen if the user or iQmetrix
                        revoked or expired an access token. To fixsorry fo, you should re-
                        authenticate the user.
                403:
                    description: |
                        Bad OAuth request (wrong consumer key, bad nonce, expired
                        timestamp...). Unfortunately, re-authenticating the user won"t help here.
        settings:
          authorizationUri: https://accountsint.iqmetrix.net/v1/oauth2/authorize
          accessTokenUri: https://accountsint.iqmetrix.net/v1/oauth2/tokenn
          authorizationGrants: [ owner ]
schemas:
  - MappingReferenceData: |
      {
        "name": "MappingReferenceData",
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Mappings": { "type": "array", "arrayType": "object", "description": "Array, that consists of multiples of the following", "isNested": "true", "ref": "att-auth-proxy.MappingReference" }
        }
      }
  - MappingReference: |
      {
        "exclude": "true",
        "name": "MappingReference",
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "MyLoginsCspGroup": { "type": "string", "description": "Alphabetic string that corresponds to the column 'MyLogins CSP Group' in the mapping spreadsheet", "example": "CKPDEM" },
          "TrainingComplianceCspGroup": { "type": "string", "description": "Alphabetic string that corresponds to the column 'Training Compliance CSP Group' in the mapping spreadsheet", "example": "CKUNTM" },
          "RQSecurityRoleName": { "type": "string", "description": "Alphabetic string that corresponds to the column 'Resulting Base RQ Profile' in the mapping spreadsheet", "example": "Dealer Store Manager Basic" },
          "IsDealerSpecific":{ "type": "boolean", "description": "A flag to indicate if the service will prepend the user's dealer specific prefix to the RQSecurityRoleName to find the matching security role", "example": "false" }
        }
      }    
  - SetPrefix: |
      {
        "exclude": "true",
        "name": "SetPrefix",
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "UserName": { "type": "string", "example": "sample@iqmetrix.com" },
          "SecurityRolePrefix": { "type": "string", "putDescription": "The prefix that will be pre-pended to the user's Hub security role", "example": "iQMetrix" }
        },
        "required": [ "UserName", "SecurityRolePrefix" ]
      }         
/users({UserId}):
  uriParameters:
    UserId:
      displayName: UserId
      type: integer
      example: 12321
      description: Identifier for a {{User}}
      required: true
  put:
    headers:
      Authorization:
        example: Bearer (Access Token)
        description: See <a href='/api/authentication/#obtaining-an-access-token'>Obtaining an Access Token</a>        
      Accept:
        example: application/json     
    displayName: Setting a Prefix for a User
    description: |
      The prefix will be prepended to the User's role with whitespace in the form `{SecurityRolePrefix} {rqSecurityRoleName}`.
    body:
      application/json:
        schema: SetPrefix
    responses:
      200:
        body:
          application/json:
            schema: SetPrefix
/cspGroupMappingReference:
  type:
    singularEndpointReadOnly:
      resource: MappingReferenceData
  get:
    displayName: Getting the Security Role Mapping Reference Data
    responses:
        200:
            body:
                application/json:
                  example: |
                      {
                        "Mappings": [
                            {
                                "MyLoginsCspGroup": "CKPDEM",
                                "TrainingComplianceCspGroup": null,
                                "RQSecurityRoleName": "Chief of Staff",
                                "IsDealerSpecific": false
                            },
                            {
                                "MyLoginsCspGroup": "CKPDEM",
                                "TrainingComplianceCspGroup": "CKUNTM",
                                "RQSecurityRoleName": "Dealer Store Manager Basic",
                                "IsDealerSpecific": false
                            },
                            {
                                "MyLoginsCspGroup": "CKPDPM",
                                "TrainingComplianceCspGroup": null,
                                "RQSecurityRoleName": "Dealer Principal",
                                "IsDealerSpecific": false
                            },
                            {
                                "MyLoginsCspGroup": "CKPDPM",
                                "TrainingComplianceCspGroup": "CKUNTM",
                                "RQSecurityRoleName": "Dealer Store Manager Basic",
                                "IsDealerSpecific": false
                            }
                            ...
                        ]                      
                      }
