#%RAML 0.8
title: RQ Data Connect Bridge
baseUri: https://rqdataconnect{UrlSuffix}.iqmetrix.net
baseUriParameters:
  UrlSuffix:
    description: Suffix that defines the environment
    example: int
    type: string
documentation:
  - title: author
    content: | 
      RQ
  - title: overview
    content: |

      RQ Data Connect Bridge is intended to be an alternative to database replication, and allows you to retrieve tables from your RQ database.

      For examples of how RQ Data Connect Bridge can be used, see [Extended Examples](#extended-examples).

      #### Authentication

      RQ Data Connect Bridge supports many different methods of authentication, see {{AuthenticationOptions}}.     
  - title: extended-examples
    content: |

        These examples are intended to illustrate some suggested uses of RQ Data Connect Bridge.

        ### Data Replication

        In this example, we will get a list of time off requests made since January 1st, 2016, which are stored in the table iQplanner_HR_RequestedTimeOff.

        First we must see if there is any data using [Getting Changes to a Table in RQ](#getting-changes-to-a-table-in-rq). This will return a list of "Deltas" or changes to the table since a specified date.

        ##### Example Request

        ```
        GET https://rqdataconnectdemo.iqmetrix.net/bridge/current/delta?Table=iQplanner_HR_RequestedTimeOff&RowDateTime=2016-01-01T00:00:00.000Z
        Authorization: Bearer (Access Token)
        ```

        ##### Example Response

        ```
        [
          {
            "Table": "iQplanner_HR_RequestedTimeOff",
            "DeltaCount": 26,
            "DeltaTimeSec": 10844356
          }
        ]
        ```

        From the response we can see there have been changes to 26 rows in the iQplanner_HR_RequestedTimeOff table since January 1st, 2016.

        Next we must ensure the application we are building knows what the iQplanner_HR_RequestedTimeOff table looks like.

        This data can be obtained using the [Getting Table Schemas in Latest RQ](#getting-table-schemas-in-latest-rq).

        ##### Example Request

        ```
        GET https://rqdataconnectdemo.iqmetrix.net/bridge/current/schema
        Authorization: Bearer (Access Token)
        ```

        ##### Example Response

        ```
        [
          ...,
          {
            "TableName": "iQplanner_HR_RequestedTimeOff",
            "Column_Name": "RequestID",
            "Type": "int",
            "Length": null,
            "ORDINAL_POSITION": 1
          },
          {
            "TableName": "iQplanner_HR_RequestedTimeOff",
            "Column_Name": "EmployeeID",
            "Type": "int",
            "Length": null,
            "ORDINAL_POSITION": 2
          },
          ...
        ]
        ```

        From the response we can see the format of the data that will be returned in the next request, using [Getting Rows from a Table in RQ](#getting-rows-from-a-table-in-rq)

        ##### Example Request

        ```
        GET https://rqdataconnectdemo.iqmetrix.net/bridge/current/data?Table=iQplanner_HR_RequestedTimeOff
        Authorization: Bearer (Access Token)
        ```

        ##### Example Response

        ```
        [
          {
            "RequestID": 39,
            "EmployeeID": 31,
            "DateFrom": "2011-11-05T08:30:00",
            "DateTo": "2011-11-05T17:30:00",
            "Type": 1,
            "Status": 1,
            "Notes": "Dentist",
            "ApprovedByID": 8,
            "ManagerNotes": "",
            "Paid": false,
            "PaidNotes": "",
            "TimeZoneID": 5,
            "SubmitDate": "2011-08-31T08:06:57.09",
            "RequestedByID": null,
            "DaysRequested": null,
            "RowThumbprint": "ac5a4ffa-3a4c-4424-9d88-4743517b8549",
            "RowInserted": "2011-08-31T08:06:57.09",
            "RowUpdated": null,
            "Operation": "Inserted"
          },
          ...
        ]
        ``` 
  - title: errors
    content: |
      | HTTP Status Code | Description | How to Resolve |
      |:-----------------|:------------|:---------------|
      | `HTTP 400` | `Bad Request` | Ensure request body is formatted properly |
      | `HTTP 401` | `Token is invalid` | Ensure Access Token is valid and has not expired | 
      | `HTTP 403` | `Unauthorized` | Ensure Access Token is valid and user has appropriate security |
      | `HTTP 404` | `Not Found` | Ensure URI is valid |
      | `HTTP 429` | `Too Many Requests` | See [Rate Limiting](/api/#rate-limiting) |
      | `HTTP 500` | `Unexpected Error` | See Message in response for more information |
        
resourceTypes:
  - collectionReadOnly:
      get:
          headers:
            Authorization:
              example: Bearer (Access Token)
              required: false
              description: Bearer token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
            Accept-Encoding:
              example: gzip
              required: false
              description: Compression algorithm. For other methods of compression, see {{CompressionOptions}}
          responses:
            200:
                body:
                    application/json:
                      schema: <<resource>>
                    application/JsonDataTable:
                      schema: <<resource>>
                    text/xml:
                      schema: <<resource>>
                    text/XmlDataTable:
                      schema: <<resource>>
                    text/csv:
                      schema: <<resource>>
                    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
                      schema: <<resource>>
schemas:
  - TableColumn: |
      {
        "name": "TableColumn",
        "description": "Each table in the latest version of RQ will have a TableColumn resource for each of its columns",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "TableName": { "type": "string", "description": "Name of the table", "example": "iQclerk_ARPaymentInvoicesAndPayments" },
          "Column_Name": { "type": "string", "description": "Name of the column", "example": "ReferenceNumber" },
          "Length": { "type": "integer", "description": "Maximum acceptable input size, where applicable", "example": "30" },         
          "ORDINAL_POSITION": { "type": "integer", "description": "Position of the column in the table", "example": "8" },
          "Type": { "type": "string", "description": "Database type", "example": "varchar" }
        }
      }  
  - Delta: |
      {
        "name": "Delta",
        "description": "A resource representing changes to a table in the latest version of RQ.",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "DeltaCount": { "type": "integer", "description": "Number of rows that have changes", "example": "68" },
          "DeltaTimeSec": { "type": "integer", "description": "", "example": "28704556" },
          "Table": { "type": "string", "description": "Name of a table in the latest version of RQ", "example": "CarrierIntegrationCustomerHandsets" }
        }
      }
  - DataExample: |
      {
        "exclude": "true",
        "example": "true",
        "name": "DataExample",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "CarrierCustomerHandsetID": {  "type": "guid", "example": "7f1b91e2-9692-4efe-923b-7bc90720ccb8" },
          "CarrierCustomerID": {  "type": "guid", "example": "62c24270-503a-4de4-9d75-416c92a748d7" },
          "SaleInvoiceID": {  "type": "integer", "example": "-1" },
          "StoreID": {  "type": "integer", "example": "3" },
          "PhoneMake": {  "type": "string", "example": "null" },
          "PhoneModel": {  "type": "string", "example": "Unknown Device" },
          "ESN": {  "type": "string", "example": "" },
          "IMEI": {  "type": "string", "example": "354493046773064" },
          "CustomTelephoneNumber": {  "type": "string", "example": "8186368202" },
          "BAN": {  "type": "string", "example": "null" },
          "SIM": {  "type": "string", "example": "89014103254674079938" },
          "MDN": {  "type": "string", "example": "null" },
          "ActivationDate": {  "type": "datetime", "example": "2014-10-01T15:00:12.05" },
          "ExpiryDate": {  "type": "datetime", "example": "2014-10-01T15:00:12.05" },
          "RateORServicePlanName": {  "type": "string", "example": "null" },
          "RateORServicePlanDescription": {  "type": "string", "example": "null" },
          "RateORServicePlanInclusions": {  "type": "string", "example": "null" },
          "RateORServicePlanSOC": {  "type": "string", "example": "FN2NM0A60" },
          "RateORServicePlanTerm": {  "type": "string", "example": "null" },
          "RateORServicePlanFeatures": {  "type": "string", "example": "null" },
          "RateORServicePlanContractTerm": {  "type": "string", "example": "2" },
          "SalesRepName": {  "type": "string", "example": "null" },
          "DealerName": {  "type": "string", "example": "HJG6E" },
          "BillingCycle": {  "type": "string", "example": "null" },
          "BillingCycleDate": {  "type": "integer", "example": "17" },
          "DepositAmount": {  "type": "decimal", "example": "0.00" },
          "BillingCode": {  "type": "string", "example": "" },
          "IsActivatedIQ": {  "type": "boolean", "example": "0" },
          "RateORServicePlan2SOC": {  "type": "string", "example": "null" },
          "RateORServicePlan2Description": {  "type": "string", "example": "null" },
          "DealerCode": {  "type": "string", "example": "null" },
          "CompanyCode": {  "type": "string", "example": "null" },
          "PortInNumber": {  "type": "string", "example": "null" },
          "DepositIndicator": {  "type": "string", "example": "No Deposit" },
          "FlowType": {  "type": "string", "example": "null" },
          "ActivationTermType": {  "type": "string", "example": "null" },
          "IsBYOD": {  "type": "boolean", "example": "null" },
          "Priority": {  "type": "integer", "example": "null" },
          "CarrierServiceResource": {  "type": "string", "example": "null" },
          "RowThumbprint": {  "type": "guid", "example": "1c1103c2-db83-4df9-a86d-1b649bf304ee" },
          "RowInserted": {  "type": "datetime", "example": "2014-10-01T15:00:12.05" },
          "RowUpdated": {  "type": "datetime", "example": "2014-10-01T15:00:12.05" },
          "Operation": {  "type": "string", "example": "Inserted" }
        }
      }    
/bridge/current/schema?Auth={Auth}&Response={Response}: 
  uriParameters:
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: TableColumn
  get:
    displayName: Getting Table Schemas in Latest RQ
    description: |
      This request will return a list of the columns in each table in the latest version of RQ.  
/bridge/current/data?Table={TableName}&Auth={Auth}&Response={Response}: 
  uriParameters:
    TableName:
      type: string
      example: CarrierIntegrationCustomerHandsets
      description: Name of a Table in RQ, for a complete list see <a href="#getting-schema-for-the-latest-version-of-rq">Getting Schema for the Latest Version of RQ</a>
      required: true
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: DataExample
  get:
    displayName: Getting Rows from a Table in RQ
    description: This request will return the contents of a table in the latest version of RQ. The response to this request will match the appropriate table schema defined in [Getting Table Schemas in Latest RQ](#getting-table-schemas-in-latest-rq).
/bridge/current/delta?Table={TableName}&RowDateTime={RowDateTime}&Auth={Auth}&Response={Response}:
  uriParameters:
    TableName:
      type: string
      example: CarrierIntegrationCustomerHandsets
      description: Name of a Table in RQ, for a complete list see <a href="#getting-schema-for-the-latest-version-of-rq">Getting Schema for the Latest Version of RQ</a>
      required: true
    RowDateTime:
      type: string
      example: 2015-07-14 16:26:39.000
      description: Changes since this date will be returned in the response
      required: true
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: Delta
  get:
    displayName: Getting Changes to a Table in RQ 
    description: |
      This request will return a summary of the changes or "deltas" in a table in the latest version of RQ since a specified date.