#%RAML 0.8
title: StatFlo Reports
baseUri: https://rqdataconnect{UrlSuffix}.iqmetrix.net
baseUriParameters:
  UrlSuffix:
    description: Suffix that defines the environment
    example: int
    type: string
documentation:
  - title: exclude
    content: true
  - title: overview
    content: |

      To get started, see [RQ Data Connect Guide](/guides/rq-data-connect/).    

      #### Note

      For reports that provide optional URI parameters for filtering at different levels (ForWho/ForWhoIDs/LocationType/LocationTypeIDs), omitting these values will run the report at the default company level.

      #### Authentication

      This API supports many different methods of authentication, see {{AuthenticationOptions}}.   
  - title: errors
    content: |
      | HTTP Status Code | Description | How to Resolve |
      |:-----------------|:------------|:---------------|
      | `HTTP 400` | `Bad Request` | Ensure request body is formatted properly |
      | `HTTP 401` | `Token is invalid` | Ensure Access Token is valid and has not expired | 
      | `HTTP 403` | `Unauthorized` | Ensure Access Token is valid and user has appropriate security |
      | `HTTP 404` | `Not Found` | Ensure URI is valid |
      | `HTTP 429` | `Too Many Requests` | See [Rate Limiting](/api/#rate-limiting) |
      | `HTTP 500` | `Unexpected Error` | See Message in response for more information |        
resourceTypes:
  - collectionReadOnly:
      get:
          headers:
            Authorization:
              example: Bearer (Access Token)
              required: false
              description: Bearer token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
            Accept-Encoding:
              example: gzip
              required: false
              description: Compression algorithm. For other methods of compression, see {{CompressionOptions}}
          responses:
            200:
                body:
                    application/json:
                      schema: <<resource>>
                    application/JsonDataTable:
                      schema: <<resource>>
                    text/xml:
                      schema: <<resource>>
                    text/XmlDataTable:
                      schema: <<resource>>
                    text/csv:
                      schema: <<resource>>
                    application/vnd.openxmlformats-officedocument.spreadsheetml.sheet:
                      schema: <<resource>>
schemas:
  - ActivationGrossProfitReportData: |
      {
        "type": "array",
        "name": "ActivationGrossProfitReportData",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": { 
          "InvoiceDate": { "type": "datetime", "database": "DATETIME", "example": "2016-10-12T09:16:24.63", "description": "Date - date of the transaction" },  
          "InvoiceID": { "type": "integer", "database": "INT", "example": "129920", "description": "Identifier for an invoice in RQ" },  
          "InvoiceIDByStore": { "type": "string", "database": "VARCHAR(14)", "example": "84WEAIN15624", "description": "Invoice # - invoice number of the transaction" },  
          "StoreTypeName": { "type": "string", "database": "NVARCHAR(MAX)", "example": "Retail Store", "description": "Location Type - location type where the transaction was performed" },  
          "LocationName": { "type": "string", "database": "NVARCHAR(MAX)", "example": "84 West", "description": "Location -  location where the transaction occurred" },  
          "Profit": { "type": "decimal", "database": "MONEY", "example": "667.99", "description": "Profit - amount of profit made on the activation, includes the total profit for the parameters run" },  
          "CustomerID": { "type": "integer", "database": "INT", "example": "108560", "description": "Identifier for the customer in RQ" },  
          "CustomerName": { "type": "string", "database": "VARCHAR(151)", "example": "AAA AND ASSOCIATES", "description": "Customer - name of the customer on the invoice" },  
          "PhoneDescription": { "type": "string", "database": "NVARCHAR(MAX)", "example": "Apple iPhone 6 Plus 16GB White - AT&T", "description": "Phone - phone used in the activation" },  
          "PhoneNumber": { "type": "string", "database": "VARCHAR(30)", "example": "3065014785", "description": "Phone # - phone number entered into the Phone Activation Wizard" },  
          "TermDescription": { "type": "string", "database": "NVARCHAR(MAX)", "example": "CRU 2 YR Business New Act", "description": "Term - term selected with the activation" },  
          "RatePlanDescription": { "type": "string", "database": "NVARCHAR(MAX)", "example": "2 YR CRU Business Legacy Plan $0.01 - $9.99", "description": "Rate Plan - rate plan selected for the activation" },  
          "VendorAccountName": { "type": "string", "database": "VARCHAR(100)", "example": "AT&T", "description": "Vendor Account - vendor account used in the activation" },  
          "EmployeeName": { "type": "string", "database": "VARCHAR(51)", "example": "iQmetrix User", "description": "Employee - sales person on the invoice" },  
          "DistrictName": { "type": "string", "database": "NVARCHAR(MAX)", "example": "Valley Area District", "description": "District - district the store is in" },  
          "RegionName": { "type": "string", "database": "NVARCHAR(MAX)", "example": "Region A", "description": "Region - region the store is in" },  
          "ChannelName": { "type": "string", "database": "NVARCHAR(MAX)", "example": "Regina Channel", "description": "Channel - channel the store is in" }  
        }  
      }
  - CouponSummaryReportData: |
      {  
        "type": "array",
        "name": "CouponSummaryReportData",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": { 
          "Date": { "type": "datetime", "database": "DATETIME", "example": "2016-01-01T00:00:00", "description": "Date - every day in the date range selected" },  
          "QuantityApplied": { "type": "integer", "database": "INT", "example": "1", "description": "Qty Applied - total quantity of coupons applied for the day" },  
          "QuantityRefunded": { "type": "integer", "database": "INT", "example": "1", "description": "Qty Refunded - total quantity of coupons refunded for the day" },  
          "NetQuantity": { "type": "integer", "database": "INT", "example": "0", "description": "Net Qty - net quantity of coupons for the day calculated as Qty Applied - Qty Refunded" },  
          "TotalValue": { "type": "decimal", "database": "MONEY", "example": "-10", "description": "Total Value - net dollar value of all coupons for the day" }  
        }  
      }
  - CustomerListReportData: |
      {
        "name": "CustomerListReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Address": {  "type": "string", "database": "VARCHAR(50)", "description": "Address - first line of the address", "example": "12 Hello St." },
          "Address2": {  "type": "string", "database": "VARCHAR(50)", "description": "Address 2 - second line of the address, if necessary", "example": "n/a" },
          "BillingAccountNumber": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "BAN -  if your company uses BAN you will enter it in the Customer profile and it will show here", "example": "" },
          "City": {  "type": "string", "database": "VARCHAR(50)", "description": "City - customer's city", "example": "Fargo" },
          "ContactNumber": {  "type": "string", "database": "VARCHAR(200)", "description": "Contact # - the number that is selected on the customer's profile, it can be any of the number options there", "example": "5555555555" },
          "ContactTypeName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Contact Type - as defined in General Customer Setup and assigned in the Custom Fields section on the customer's profile", "example": "" },
          "Country": {  "type": "string", "database": "VARCHAR(50)", "description": "Country - customer's country", "example": "United States" },
          "CustomerCompanyName": {  "type": "string", "database": "VARCHAR(50)", "description": "Company Name - may be blank depending on the kind of customer", "example": "KENTEL" },
          "CustomerFirstName": {  "type": "string", "database": "VARCHAR(50)", "description": "First Name - may be blank depending on the kind of customer", "example": "Carrie" },
          "CustomerID": {  "type": "integer", "database": "INT", "description": "Identifier for a Customer in RQ", "example": "2108754" },
          "CustomerLastName": {  "type": "string", "database": "VARCHAR(50)", "description": "Last Name - may be blank depending on the kind of customer", "example": "Madison" },
          "DateCreated": {  "type": "datetime", "database": "DATETIME", "description": "Created On - day and time the customer's profile was created", "example": "2016-01-26T20:55:53.227" },
          "DeclineToProvideEmail": {  "type": "boolean", "database": "BIT", "description": "Decline Email - the option for customers to decline email", "example": "false" },
          "Email": {  "type": "string", "database": "VARCHAR(200)", "description": "Email - may be blank, if so, the context menu will not have the Email Customer option", "example": "carry@test.iq" },
          "EmployeeName": {  "type": "string", "database": "VARCHAR(51)", "description": "Created By - employee who created the profile", "example": "iQmetrix Employee" },
          "EmployeeNameAssignedTo": {  "type": "string", "database": "VARCHAR(51)", "description": "Assigned To - may be blank if the customer has not been assigned to an employee", "example": "iQmetrix Employee" },
          "IndustryTypeName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Industry Type - as defined in General Customer Setup and assigned in the Custom Fields section on the customer's profile", "example": "" },
          "MultiLevelPriceID": {  "type": "integer", "database": "INT", "description": "Pricing Group - as defined in Multi-Level Pricing - Setup and assigned in the Discount Level field in the More Information section on the customer's profile", "example": "1" },
          "NumberOfActivations": {  "type": "integer", "database": "INT", "description": "# of Activations - number of Activations the customer has completed as recorded in RQ", "example": "0" },
          "PositionTypeName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Position Type - as defined in General Customer Setup and assigned in the Custom Fields section on the customer's profile", "example": "" },
          "PostalCode": {  "type": "string", "database": "VARCHAR(15)", "description": "Zip/Postal Code - zip code (USA) or postal code (Canada)", "example": "90123" },
          "Province": {  "type": "string", "database": "VARCHAR(50)", "description": "State/Province - customer's state or province", "example": "ND" },
          "TracPointMemberNumber": {  "type": "string", "database": "VARCHAR(30)", "description": "Member # - this number is automatically generated when a new customer is created", "example": "C2981754hduw" },
          "TypeOfCustomer": {  "type": "integer", "database": "INT", "description": "Type Of Customer - 0 for Company, or 3 for Individual", "example": "3" },
          "VIPCustomer": {  "type": "byte", "database": "TINYINT", "description": "VIP Customer - will be checked if this is a VIP Customer ", "example": "0" }
        }
      }  
  - EmployeeMasterListReportData: |
      {
        "name": "EmployeeMasterListReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Assigned Groups": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Assigned Groups - states the groups assigned to the employee", "example": "Sales Representative" },
          "Assigned Locations": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Assigned Locations - states the locations assigned to the individual", "example": "84 West Target Dothan Wiregrass Commons Mall - Test Long Store Name Here" },
          "City": {  "type": "string", "database": "VARCHAR(50)", "description": "City - city of the employee as entered on their profile", "example": "Dothan" },
          "Clear Fingerprints": {  "type": "string", "database": "VARCHAR(2)", "description": "Clear Fingerprints - this will allow you to clear fingerprints", "example": "No" },
          "Commission Group": {  "type": "string", "database": "VARCHAR(50)", "description": "Commission Group - commission group of the employee as entered on their profile", "example": "Sales Representative" },
          "Compensation Type": {  "type": "string", "database": "VARCHAR(21)", "description": "Compensation Type - compensation type of the employee as entered on their profile", "example": "Commission" },
          "Country": {  "type": "string", "database": "VARCHAR(50)", "description": "Country - country of the employee as entered on their profile", "example": "USA" },
          "Disabled": {  "type": "string", "database": "VARCHAR(3)", "description": "Disabled - indicates whether or not the employee is disabled", "example": "No" },
          "Email Address": {  "type": "string", "database": "VARCHAR(50)", "description": "Email Address - email address of the employee as entered on their profile (in the Email Settings section)", "example": "hilary@kentel.com" },
          "Email Display Name": {  "type": "string", "database": "VARCHAR(50)", "description": "Email Display Name - email display name of the employee as entered on their profile (in the Email Settings section)", "example": "hilary@kentel.com" },
          "Email Password": {  "type": "string", "database": "VARCHAR(1)", "description": "Email Password - email password of the employee as entered on their profile (in the Email Settings section)", "example": "test" },
          "Email Server": {  "type": "string", "database": "VARCHAR(50)", "description": "Email Server - email server of the employee as entered on their profile (in the Email Settings section)", "example": "outlook.kentel.com" },
          "Email User Name": {  "type": "string", "database": "VARCHAR(50)", "description": "Email Username -email username of the employee as entered on their profile (in the Email Settings section)", "example": "hilary" },
          "Employee ID": {  "type": "integer", "database": "INT", "description": "Identifier for the employee in RQ", "example": "60" },
          "Employee Name": {  "type": "string", "database": "VARCHAR(51)", "description": "Employee Name - name of the employee as entered on their profile", "example": "Hillary Oliver" },
          "Fingerprint Enabled": {  "type": "string", "database": "VARCHAR(3)", "description": "Fingerprint Entered - indicates if the employee has fingerprints entered", "example": "No" },
          "Frequency": {  "type": "string", "database": "VARCHAR(12)", "description": "Frequency - compensation frequency of the employee as entered on their profile", "example": "N/A" },
          "FrequencyEffective": {  "type": "string", "database": "NVARCHAR(4000)", "description": "Frequency Effective - the frequency effective date of the employee as entered on their profile", "example": "Jan 10 2011" },
          "Gender": {  "type": "string", "database": "VARCHAR(9)", "description": "Gender - gender of the employee as entered on their profile", "example": "Male" },
          "ID #": {  "type": "string", "database": "VARCHAR(25)", "description": "ID # - employees ID listed under the admin tab of the profile", "example": "912345987654321" },
          "Image Uploaded": {  "type": "string", "database": "VARCHAR(3)", "description": "Image Uploaded - indicates if the employee has a profile picture uploaded", "example": "No" },
          "Internal": {  "type": "string", "database": "VARCHAR(12)", "description": "Interval - compensation interval of the employee as entered on their profile", "example": "N/A" },
          "Intrgration Username": {  "type": "string", "database": "VARCHAR(255)", "description": "Username", "example": "hilary.kentel" },
          "Job Title": {  "type": "string", "database": "VARCHAR(50)", "description": "Job Title - job title of the employee as entered on their profile", "example": "Wireless Consultant" },
          "Language": {  "type": "string", "database": "VARCHAR(255)", "description": "Language - employees primary language", "example": "en-us" },
          "Locked": {  "type": "string", "database": "VARCHAR(3)", "description": "Locked - employee is locked so they can not be accessed", "example": "No" },
          "Part Time": {  "type": "integer", "database": "INT", "description": "Part Time - indicates if the employee is part time", "example": "0" },
          "Personal Days Available": {  "type": "integer", "database": "INT", "description": "Personal Days Available - will state the personal days available", "example": "0" },
          "Personal Email": {  "type": "string", "database": "VARCHAR(50)", "description": "Personal Email - personal email of the employee as entered on their profile", "example": "hilary@kentel.com" },
          "Primary Location": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Primary Location - primary location of the employee as entered on their profile", "example": "Corporate Office" },
          "Rate Effective": {  "type": "string", "database": "NVARCHAR(4000)", "description": "Rate Effective - rate effective date of the employee as entered on their profile", "example": "Jan 10 2011" },
          "Rate": {  "type": "decimal", "database": "MONEY", "description": "Rate - compensation rate of the employee as entered on their profile", "example": "0" },
          "Role": {  "type": "string", "database": "VARCHAR(1)", "description": "Role - role of the employee as entered on their profile", "example": "Store Manager" },
          "Security Role": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Security Role - security role of the employee as entered on their profile", "example": "Sales Representative" },
          "Sick Days Available": {  "type": "integer", "database": "INT", "description": "Sick Days Available - will state the sick days available", "example": "0" },
          "Start Date": {  "type": "string", "database": "NVARCHAR(4000)", "description": "Start Date - the start date of the employee", "example": "Dec 05 2010" },
          "State / Prov": {  "type": "string", "database": "VARCHAR(50)", "description": "State/Prov - state or province of the employee as entered on their profile", "example": "AL" },
          "Supervisor": {  "type": "string", "database": "VARCHAR(51)", "description": "Supervisor - supervisor of the employee as entered on their profile", "example": "Robyn Roberts" },
          "Termination Date": {  "type": "string", "database": "NVARCHAR(4000)", "description": "Termination Date - states the termination date of the employee", "example": "Today" },
          "Termination Notes": {  "type": "string", "database": "VARCHAR(255)", "description": "Termination Notes - states the notes for the termination", "example": "Vacation days to be paid" },
          "Username": {  "type": "string", "database": "VARCHAR(51)", "description": "Username - username of the employee as entered in their profile", "example": "Hillary.Oliver" },
          "Vacation Days Available": {  "type": "integer", "database": "INT", "description": "Vacation Days Available - will state the vacation days available", "example": "0" },
          "Work #": {  "type": "string", "database": "VARCHAR(50)", "description": "Work # - work number of the employee as entered on their profile", "example": "3347020770" }
        }
      }         
  - GraphedPerformanceMetrixReportData: |
      {
        "name": "GraphedPerformanceMetrixReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {        
          "ID": {  "type": "integer", "database": "INT", "description": "Identifier for a performance metrix group in RQ", "example": "6" },
          "Name": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Name of a performance metrix group in RQ", "example": "51247 Test_update" },
          "AttachmentRate": {  "type": "string", "database": "VARCHAR(23)", "description": "Comparison of Performance Groups for the Attachment Rate displayed as a ratio", "example": "1249 : 2" },
          "AttachmentRateTarget": {  "type": "string", "database": "VARCHAR(23)", "description": "Attachment rate target", "example": "0 : 0" },
          "DisplayFormat": {  "type": "integer", "database": "INT", "description": "1: Ratio Format, 2: Percentage Format", "example": "2" },
          "IsAttachmentRate": {  "type": "boolean", "database": "BIT", "description": "A flag to indicate if performance group is an attachment rate", "example": "true" },
          "Margin": {  "type": "decimal", "database": "MONEY", "description": "Margin on sales in this performance group", "example": "null" },
          "MarginTarget": {  "type": "decimal", "database": "MONEY", "description": "Margin target", "example": "null" },
          "Priority": {  "type": "integer", "database": "INT", "description": "Priority", "example": "-1" },
          "Profit": {  "type": "decimal", "database": "MONEY", "description": "Net profit amount of sales in this performance group", "example": "null" },
          "ProfitTarget": {  "type": "decimal", "database": "MONEY", "description": "Profit target", "example": "null" },
          "Quantity": {  "type": "integer", "database": "INT", "description": "Net count of SKUs sold in this performance group", "example": "null" },
          "QuantityTarget": {  "type": "integer", "database": "INT", "description": "Quantity target", "example": "null" },
          "Sales": {  "type": "decimal", "database": "MONEY", "description": "Net dollar amount of sales in this performance group", "example": "null" },
          "SalesTarget": {  "type": "decimal", "database": "MONEY", "description": "Sales target", "example": "null" }
        }
      }   
  - GraphedPerformanceMetrixBreakdownReportData: |
      {
        "name": "GraphedPerformanceMetrixBreakdownReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "ID": {  "type": "integer", "database": "INT", "description": "Internal idenfier in RQ", "example": "1" },
          "Name": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Name of company, region, division, location or employee depending on ByWho URL parameter", "example": "84 West" },
          "GroupInvoiceCount": {  "type": "integer", "database": "INT", "description": "This number represents the size of the section of pie graph", "example": "839" },
          "IsAttachmentRate": {  "type": "boolean", "database": "BIT", "description": "A flag to indicate if performance group is an attachment rate", "example": "false" },
          "Margin": {  "type": "decimal", "database": "MONEY", "description": "Margin", "example": "-1691.5747" },
          "MarginTarget": {  "type": "decimal", "database": "DECIMAL", "description": "Margin target", "example": "0" },
          "Profit": {  "type": "decimal", "database": "MONEY", "description": "Profit", "example": "-45860859.08" },
          "ProfitTarget": {  "type": "decimal", "database": "MONEY", "description": "Profit target", "example": "0" },
          "Quantity": {  "type": "integer", "database": "INT", "description": "Quantity", "example": "530" },
          "QuantityTarget": {  "type": "integer", "database": "INT", "description": "Quantity target", "example": "0" },
          "Sales": {  "type": "decimal", "database": "MONEY", "description": "Total sales", "example": "27111.34" },
          "SalesTarget": {  "type": "decimal", "database": "MONEY", "description": "Sales target", "example": "0" },
          "TotalInvoiceCount": {  "type": "integer", "database": "INT", "description": "This number represents the total size of the graph ", "example": "2772" }
        }
      }       
  - LocationMasterListReportData: |
      {
        "name": "LocationMasterListReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Abbreviation": {  "type": "string", "database": "VARCHAR(5)", "description": "Abbreviation - this cannot be edited", "example": "LIT22" },
          "Address": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Address - address assigned to location", "example": "4970 Hillside Avenue" },
          "AddressVerified": {  "type": "string", "database": "VARCHAR(12)", "description": "Address Verified - if the address can not be verified then you will have the option to edit the Latitude and Longitude to verify it", "example": "Not Verified" },
          "AdjustDST": {  "type": "boolean", "database": "BIT", "description": "Adjust DST - check if the location adjusts for daylight savings", "example": "false" },
          "BankDetails": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Bank Details - the Banks name for the location", "example": "CashSmart" },
          "CashPolicy": {  "type": "string", "database": "VARCHAR(13)", "description": "Cash Policy - states the cash policy (single/multi-drawer)", "example": "Single-Drawer" },
          "ChannelName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Channel - channel the region is assigned to", "example": "Alabama" },
          "City": {  "type": "string", "database": "VARCHAR(50)", "description": "City - city the location resides in", "example": "Kansas" },
          "Comment_on_OE": {  "type": "boolean", "database": "BIT", "description": "Comment on OE - show product and location comments on sales order", "example": "false" },
          "Country": {  "type": "string", "database": "VARCHAR(50)", "description": "Country - country the location is located in", "example": "United States" },
          "DepositTaken": {  "type": "decimal", "database": "MONEY", "description": "Deposit Taken - lists the deposit if applicable", "example": "0" },
          "Disabled": {  "type": "integer", "database": "INT", "description": "Disable - indicates if the location is enabled or disabled", "example": "1" },
          "DistrictName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "District - district the location is assigned to", "example": "Smithton" },
          "EmailAddress": {  "type": "string", "database": "VARCHAR(255)", "description": "Email Address - email address assigned to the location", "example": "abarea@kentel.com" },
          "FaxNumber": {  "type": "string", "database": "VARCHAR(10)", "description": "Fax # - Fax # listed under the location", "example": "5555555555" },
          "GeneralLocationNotes": {  "type": "string", "database": "VARCHAR(255)", "description": "General Location Notes - notes specific to the location", "example": "note" },
          "GLCode": {  "type": "string", "database": "VARCHAR(100)", "description": "Code - coded associated to the location", "example": "-MILLH" },
          "HideCustomerAddress": {  "type": "boolean", "database": "BIT", "description": "Hide Customer Address - prevents the customers address from being seen on an invoice", "example": "false" },
          "InsuranceAmount": {  "type": "decimal", "database": "MONEY", "description": "Insurance - cost of Insurance", "example": "0" },
          "InsuranceCompany": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Insurance Company - name of the insurance company", "example": "Safefair" },
          "LandlordName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Landlord Name - name of the landlord", "example": "Jim Jones" },
          "LandlordNotes": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Landlord Notes - notes specific to the landlord", "example": "sample note" },
          "Latitude": {  "type": "decimal", "database": "DECIMAL", "description": "Latitude - latitude location of the store", "example": "50.443559" },
          "LeaseEndDate": {  "type": "datetime", "database": "DATETIME", "description": "Lease End Date - the day the lease ends", "example": "2014-12-24T00:00:00" },
          "LeaseNotes": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Lease Notes - notes specific to the lease", "example": "note" },
          "LeaseStartDate": {  "type": "datetime", "database": "DATETIME", "description": "Lease Start Date - day the lease started", "example": "2014-11-26T00:00:00" },
          "LocationCode": {  "type": "string", "database": "VARCHAR(100)", "description": "Location Code - code entered in the property details tab in the Location Setup", "example": "500" },
          "LocationEntityID": {  "type": "integer", "database": "INT", "description": "Identifier of the store as a {{Location}} in Entity Store", "example": "48540" },
          "Longitude": {  "type": "decimal", "database": "DECIMAL", "description": "Longitude - longitude location of the store", "example": "-104.612034" },
          "ManagerCommissionable": {  "type": "boolean", "database": "BIT", "description": "Manager Commissionable - indicates if the manager is commissionable.", "example": "false" },
          "ManagerEmployeeID": {  "type": "integer", "database": "INT", "description": "Manager - manager assigned to the location", "example": "233" },
          "MaxCashDrawer": {  "type": "decimal", "database": "MONEY", "description": "Max Cash Drawer - maximum amount of cash allowed in a cash drawer", "example": "0" },
          "OtherCharges": {  "type": "decimal", "database": "MONEY", "description": "Other Charges - other charges associated to the location", "example": "0" },
          "PAW_on_OE": {  "type": "boolean", "database": "BIT", "description": "PAW on OE - launch PAW on sales orders", "example": "false" },
          "Phone_on_OE": {  "type": "boolean", "database": "BIT", "description": "Force phone number for entry on sales orders", "example": "true" },
          "PhoneNumber": {  "type": "string", "database": "VARCHAR(10)", "description": "Phone # - designated number for the location", "example": "4353424234" },
          "PropertyTaxes": {  "type": "decimal", "database": "MONEY", "description": "Property Taxes - applicable property taxes", "example": "0" },
          "RegionName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Region - region the district is assigned to", "example": "Abarea" },
          "RelocationDate": {  "type": "datetime", "database": "DATETIME", "description": "Relocation Date - lists the date of the relocation if applicable", "example": "2016-02-26T00:00:00" },
          "Rent": {  "type": "decimal", "database": "MONEY", "description": "Rent - rent amount for the location", "example": "0" },
          "SaleInvoiceComment": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Sale Invoice Comment - locations sales invoice comment", "example": "Sale Invoice Comments" },
          "Serial_on_OE": {  "type": "boolean", "database": "BIT", "description": "Serial # on OE - force serial # for entry on sales orders", "example": "false" },
          "SquareFootage": {  "type": "integer", "database": "INT", "description": "Square Feet - approx square feet of the store", "example": "0" },
          "StaffLevel": {  "type": "decimal", "database": "DECIMAL", "description": "Staff Level - designated staffing level for the location", "example": "12" },
          "StateProv": {  "type": "string", "database": "NVARCHAR(3)", "description": "State/Prov - state or province the location is located in", "example": "AL" },
          "StoreID": {  "type": "integer", "database": "INT", "description": "Internal identifier for the store in RQ", "example": "1187" },
          "StoreName": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Store Name - name of the store", "example": "Dufferin Mall" },
          "StoreType": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Store Type - will state the store type", "example": "Retail Store" },
          "Taxes": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "Taxes - taxes assigned to the location", "example": "GOODS AND SERVICES TAX (GST)" },
          "TimeZone": {  "type": "string", "database": "VARCHAR(200)", "description": "Time Zone - time zone assigned to location", "example": "(GMT-06:00) Saskatchewan" },
          "UseLocationEmail": {  "type": "boolean", "database": "BIT", "description": "Use Location for Email - use the location for the email contact", "example": "false" },
          "ZipPostal": {  "type": "string", "database": "VARCHAR(15)", "description": "Zip/Postal - zip/postal for the location", "example": "90210" }          
        }
      }                
  - ProductDetailReportData: |
      {
        "name": "ProductDetailReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Activation_RowID": { "type": "guid", "description": "Internal identifier in RQ", "database": "UNIQUEIDENTIFIER", "example": "d3d65281-5201-4927-9bac-6f3a47ddf56b" },
          "AdjustedUnitPrice": { "type": "decimal", "description": "Adjusted Unit Price - price that the product was actually sold for", "database": "MONEY", "example": "25" },
          "BillingAccountNumber": {  "type": "string", "database": "NVARCHAR(MAX)", "description": "BAN -  if your company uses BAN you will enter it in the Customer profile and it will show here", "example": "" },
          "CarrierPrice": { "type": "decimal", "description": "Carrier Price - value or revenue that a carrier assigns this feature", "database": "MONEY", "example": "null" },
          "CategoryPath": { "type": "string", "description": "Category - the category the product belongs to", "database": "NVARCHAR(MAX)", "example": ">> Phones >> Galaxies" },
          "ChannelName": { "type": "string", "description": "Channel - channel for the rows location", "database": "NVARCHAR(MAX)", "example": "English Channel" },
          "Comments": { "type": "string", "description": "Invoice Comments - comments added to the invoice", "database": "TEXT", "example": "" },
          "ContractNumber": { "type": "string", "description": "Contract # - number of the contract, recorded at the time of sale", "database": "VARCHAR (50)", "example": "12345" },
          "CustomerID": { "type": "integer", "description": "Internal identifier for a customer in RQ", "database": "INT", "example": "131149" },
          "CustomerName": { "type": "string", "description": "Customer - name of the customer as entered on their profile", "database": "VARCHAR (101)", "example": "Bob Jones" },
          "DateCreated": { "type": "datetime", "description": "Sold On - date and time the invoice was tendered", "database": "DATETIME", "example": "2016-05-13T12:18:08.723" },
          "DistrictName": { "type": "string", "description": "District - district for the rows location", "database": "NVARCHAR(MAX)", "example": "Westminster" },
          "EmployeeName": { "type": "string", "description": "Sold By - name of the employee of record for the sale, i.e. the employee whose name is in the Commission box", "database": "VARCHAR (51)", "example": "iQmetrix User" },       
          "EmployeeID": { "type": "integer", "description": "Internal identifier for an employee in RQ", "database": "INT", "example": "4" },
          "GlobalProductID": { "type": "integer", "description": "Internal identifier in RQ", "database": "INT", "example": "5179" },
          "InvoicedAt": { "type": "string", "description": "Invoiced At - name of the location which takes the inventory on a refund, usually the same as Invoiced By but will be different if a second location process a refund", "database": "NVARCHAR(MAX)", "example": "100: My Network LLC - Anchorage" },
          "InvoicedAt_StoreID": { "type": "integer", "description": "Internal identifier for a store in RQ", "database": "INT", "example": "1" },
          "InvoicedBy": { "type": "string", "description": "Invoiced By - name of the location which credited with the sale, usually the same as Invoiced At but will be different if a second location process a refund", "database": "NVARCHAR(MAX)", "example": "100: My Network LLC - Anchorage" },
          "InvoicedBy_StoreID": { "type": "integer", "description": "Internal identifier for a store in RQ", "database": "INT", "example": "1" },
          "InvoiceIDByStore": { "type": "string", "description": "Invoice # - invoice number assigned by RQ", "database": "VARCHAR (14)", "example": "77224IN3" },
          "IsOrderServiceDropShipProduct": { "type": "boolean", "description": "Internal identifier in RQ", "database": "BIT", "example": "null" },
          "IsOrderServiceShippingProduct": { "type": "boolean", "description": "Internal identifier in RQ", "database": "BIT", "example": "null" },
          "ListPrice": { "type": "decimal", "description": "List Price - current price as noted on the pricing tab in the inventory console for the product", "database": "MONEY", "example": "449.95" },
          "OriginalUnitPrice": { "type": "decimal", "description": "Orig. Unit Price - original price on the invoice", "database": "MONEY", "example": "25" },
          "Priority": { "type": "integer", "description": "The order that the products were saved in on an Invoice", "database": "INT", "example": "1" },
          "ProductCouponDiscount": { "type": "decimal", "description": "Coupon discount on the product", "database": "MONEY", "example": "0" },
          "ProductIdentifier": { "type": "string", "description": "Product SKU - the RQ generated SKU", "database": "VARCHAR(12)", "example": "ASHCSA000120" },
          "ProductName": { "type": "string", "description": "Product Name - name of the product as it appears in the inventory", "database": "NVARCHAR(MAX)", "example": "Samsung Galaxy Rugby LTE" },
          "Quantity": { "type": "integer", "description": "Qty - total number of times the Product SKU appears on the invoice", "database": "INT", "example": "1" },
          "Refund": { "type": "boolean", "description": "Refund - indicates if a negative quantity of this item was sold", "database": "BIT", "example": "0" },
          "RegionName": { "type": "string", "description": "Region - region for the rows location", "database": "NVARCHAR(MAX)", "example": "London" },
          "RetailerCatalogID": { "type": "string", "description": "Internal identifier in RQ", "database": "VARCHAR (50)", "example": "null" },
          "SaleInvoice_RowID": { "type": "guid", "description": "Internal identifier in RQ", "database": "UNIQUEIDENTIFIER", "example": "8c6537ae-75a5-4155-82b2-c8647ed05f3d" },
          "SaleInvoiceID": { "type": "integer", "description": "Identifier for an invoice in RQ", "database": "INT", "example": "128962" },
          "SaleInvoiceProduct_RowID": { "type": "guid", "description": "Internal identifier in RQ", "database": "UNIQUEIDENTIFIER", "example": "0099b78f-ba02-4a91-afd4-2f7eb0fbbb06" },
          "SerialNumber": { "type": "string", "description": "Tracking # - tracking number associated with this product, serialized products only", "database": "VARCHAR (100)", "example": "1111111" },
          "SoldAsUsed": { "type": "boolean", "description": "Sold As Used - indicates the product was used when sold", "database": "BIT", "example": "false" },
          "SpecialProductID": { "type": "integer", "description": "Internal identifier in RQ", "database": "INT", "example": "0" },
          "StoreInStoreFlowIsEnabledForStore": { "type": "boolean", "description": "Internal identifier in RQ", "database": "BIT", "example": "false" },
          "StoreInStoreGrossProfit": { "type": "decimal", "description": "SIS Gross Profit - profit, calculated as Total Sales - Cost for a SIS location.", "database": "MONEY", "example": "null" },
          "StoreInStoreListPrice": { "type": "decimal", "description": "SIS List Price - Price from the store-in-store setup of the product", "database": "MONEY", "example": "null" },
          "StoreInStorePrice": { "type": "decimal", "description": "SIS Price - The default price when sold through the store-in-store flow", "database": "MONEY", "example": "null" },
          "StoreTypeName": { "type": "string", "description": "Location Type - the location type the the transaction was performed at", "database": "NVARCHAR(MAX)", "example": "Costco" },
          "TenderedBy": { "type": "string", "description": "Tendered By - name of the employee logged into RQ when the invoice was tendered", "database": "VARCHAR (51)", "example": "iQmetrix User" },
          "TenderedBy_EmployeeID": { "type": "integer", "description": "Internal identifier for an employee in RQ", "database": "INT", "example": "277" },
          "TotalCost": { "type": "decimal", "description": "Total Cost - total purchase cost for the product(s) on the invoice", "database": "MONEY", "example": "0" },
          "TotalDiscount": { "type": "decimal", "description": "Total Discount - net discount amount for the Product SKU on the particular invoice", "database": "DECIMAL (8, 4)", "example": "424.95" },
          "TotalPrice": { "type": "decimal", "description": "Total Sales - net dollar amount for the Product SKU on the particular invoice", "database": "MONEY", "example": "25" },
          "UnitCost": { "type": "decimal", "description": "Unit Cost - purchase cost per unit", "database": "MONEY", "example": "0" },
          "UnitPrice": { "type": "decimal", "description": "Sold For - price that appeared on the invoice (including hide on invoice items), i.e. negative if a refund", "database": "MONEY", "example": "25" },
          "VendorName": { "type": "string", "description": "Name for a vendor in RQ", "database": "NVARCHAR(MAX)", "example": "" },
          "VendorSKU": { "type": "string", "description": "Vendor SKU", "database": "VARCHAR(25)", "example": "" }          
        }    
      } 
  - ProductDetailReportTaxColumnData: |
      {
        "name": "ProductDetailReportTaxColumnData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "ColName": { "type": "string", "description": "Tax name", "database": "VARCHAR", "example": "T102" },
          "ColCaption": { "type": "string", "description": "Description",  "database": "NVARCHAR(MAX)", "example": "Flat tax" },
          "CreditCardPaymentType": { "type": "string", "description": "Credit card information", "database": "VARCHAR (20)", "example": "null" }       
         }
      } 
  - ProductDetailReportTaxDetailData: |
      {
        "name": "ProductDetailReportTaxDetailData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "Amount": {  "type": "decimal", "description": "Amount", "database": "MONEY ", "example": "22.5" },
          "GlobalProductID": {  "type": "integer","description": "Identifier of a Product in RQ",  "database": "INT", "example": "5179" },
          "Priority": {  "type": "integer","description": "Priority", "database": "INT", "example": "1" },
          "SaleInvoiceID": {  "type": "integer","description": "Identifier of a sale invoice in RQ",  "database": "INT", "example": "128996" },
          "SerialNumber": {  "type": "string", "description": "Serial number", "database": "VARCHAR (100) ", "example": "2222222" },
          "TaxID": {  "type": "string", "description": "Tax identifier", "database": "VARCHAR", "example": "T102" },
          "TaxName": {  "type": "string", "description": "Tax name", "database": "NVARCHAR(MAX)", "example": "Brad flat tax" }
         }
      }  
  - VendorRebateHistoryReportData: |
      {
        "name": "VendorRebateHistoryReportData",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "ActivationAssociationNumber": { "type": "integer", "description": "Every product that is part of the same activation from the Phone Activation Wizard will have the same ActivationAssociationNumber.", "database": "INT", "example": "2" },
          "ActivationRowID": { "type": "guid", "description": "Identifier in RQ", "database": "UNIQUEIDENTIFIER", "example": "0d4652a7-a673-437a-817e-4641961ba3e6" },
          "Adjusted": { "type": "string", "description": "Adjusted - indicates if the rebate was adjusted", "database": "VARCHAR(3)", "example": "No" },
          "AssociationNumber": { "type": "integer", "description": "When adding products with PAW all associated products from the sale have the same association number tied together, this value increments based on how many sales are made on that order", "database": "SMALLINT", "example": "3" },
          "CarrierPrice": { "type": "decimal", "description": "Carrier Price - value or revenue that a carrier assigns this feature", "database": "MONEY", "example": "0" },
          "ChannelName": { "type": "string", "description": "Channel - channel for the rows location", "database": "VARCHAR(100)", "example": "English Channel" },
          "ChargeBack": { "type": "datetime", "description": "Charge Back - Yes or No column for if it is a Charge Back or not", "database": "DATETIME", "example": "No" },
          "Collected": { "type": "decimal", "description": "Collected - amount received from the carrier", "database": "MONEY", "example": "null" },
          "Comments": { "type": "string", "description": "Comments - any comments that were added as part of the reconciliation process", "database": "VARCHAR(500)", "example": "" },
          "Comments2": { "type": "string", "description": "Comments2 - any comments that were added as part of the reconciliation process", "database": "VARCHAR(500)", "example": "null" },
          "ContractNumber": { "type": "string", "description": "Contract # - number of the contract, recorded at the time of sale", "database": "VARCHAR(50)", "example": "123456789" },
          "CustomerID1": { "type": "integer", "description": "Customer Identifier - customer identifier as entered on the customers profile", "database": "INT", "example": "130834" },
          "CustomerName1": { "type": "string", "description": "Customer - name of the customer as entered on their profile", "database": "VARCHAR(101)", "example": "Bob Jones" },
          "DateCreated": { "type": "datetime", "description": "Sold On - date and time the invoice was tendered", "database": "DATETIME", "example": "2016-01-04T14:33:15.737" },
          "DateReconciled": { "type": "datetime", "description": "Reconciled On - date and time the rebate was reconciled", "database": "DATETIME", "example": "null" },
          "DistrictName": { "type": "string", "description": "District - district for the rows location", "database": "VARCHAR(100)", "example": "District B2" },       
          "EmployeeID": { "type": "integer", "description": "Internal identifier for an employee in RQ, see EmployeeName", "database": "INT", "example": "0" },
          "EmployeeID1": { "type": "integer", "description": "Internal identifier for an employee in RQ, see EmployeeName1", "database": "INT", "example": "218" },
          "EmployeeName": { "type": "string", "description": "Reconciled By - name of the employee logged in when the rebate was reconciled", "database": "VARCHAR(51)", "example": "" },
          "EmployeeName1": { "type": "string", "description": "Sales Person - name of the employee of record for the sale, i.e. the employee whose name is in the Commission box", "database": "VARCHAR(51)", "example": "iQmetrix User" },
          "ExtraField": { "type": "string", "description": "Extra Field - an optional field", "database": "VARCHAR(30)", "example": "1234567890" },
          "Flagged": { "type": "string", "description": "Flagged - flagged in the Vendor Rebate Reconciliation screen", "database": "VARCHAR(3)", "example": "No" },
          "GlobalProductID": { "type": "integer", "description": "Identifier for a Product in RQ", "database": "INT", "example": "812" },
          "InvoiceComments": { "type": "string", "description": "Comments", "database": "VARCHAR(50)", "example": "" },
          "InvoicedAt": { "type": "string", "description": "Invoiced At - name of the location which takes the inventory on a refund, usually the same as Invoiced By but will be different if a second location process a refund", "database": "VARCHAR(100)", "example": "Regina Store" },
          "InvoicedAt_StoreID": { "type": "integer", "description": "Internal identifier for a store in RQ", "database": "INT", "example": "1" },
          "InvoicedBy": { "type": "string", "description": "Invoiced By - name of the location which credited with the sale, usually the same as Invoiced At but will be different if a second location process a refund", "database": "VARCHAR(100)", "example": "Regina Store" },
          "InvoicedBy_StoreID": { "type": "integer", "description": "Internal identifier for a store in RQ", "database": "INT", "example": "1" },          
          "InvoiceIDByStore": { "type": "string", "description": "Invoice # - invoice number assigned by RQ", "database": "VARCHAR(14)", "example": "HJKIIIN2" },
          "InvoiceRowID": { "type": "guid", "description": "Internal identifier in RQ", "database": "UNIQUEIDENTIFIER", "example": "db8f28cf-5017-47f4-9ccf-b90cff32185d" },
          "JournalNumber": { "type": "string", "description": "Journal # - vendor account journal on which the rebate was reconciled", "database": "VARCHAR(20)", "example": "" },
          "OriginalSaleDate": { "type": "datetime", "description": "Original Sales Date - date of the original sale", "database": "DATETIME", "example": "null" },
          "OriginalSaleInvoiceID": { "type": "integer", "description": "Internal identifier in RQ", "database": "INT", "example": "null" },
          "OriginalSaleInvoiceIDByStore": { "type": "string", "description": "Original Invoice - invoice number of the original transaction", "database": "VARCHAR(14)", "example": "null" },
          "PartialCB": { "type": "decimal", "description": "Partial CB - amount the carrier is charging back", "database": "MONEY", "example": "0" },
          "PortNumber": { "type": "string", "description": "Port Number - if entered in transaction", "database": "VARCHAR(30)", "example": "" },
          "Postal_code": { "type": "string", "description": "Zip/Postal Code - zip code (USA) or postal code (Canada)", "database": "VARCHAR(15)", "example": "56789" },
          "ProductIdentifier": { "type": "string", "description": "Product SKU - RQ generated SKU", "database": "VARCHAR(12)", "example": "ACVZRB000001" },
          "ProductName": { "type": "string", "description": "Product Name - description of the product as it appears in the inventory", "database": "VARCHAR(100)", "example": "Verizon New Act_EquipmentRebate" },
          "ProductRowID": { "type": "guid", "description": "Literally no description in the database but originates from [iQclerk_SaleInvoicesAndProducts].[RowID]", "database": "UNIQUEIDENTIFIER", "example": "27be5c76-b0ba-4a34-ba7d-fa34aba0ab9c" },
          "Quantity": { "type": "integer", "description": "Qty - total quantity of this product SKU on the invoice", "database": "INT", "example": "1" },
          "RatePlan": { "type": "string", "description": "Rate Plan - name of the rate plan", "database": "VARCHAR(100)", "example": "Act $9.99 to $20.98" },
          "RatePlan2": { "type": "string", "description": "Rate Plan 2 - second rate plan if necessary", "database": "VARCHAR(100)", "example": "" },
          "Reconciled": { "type": "string", "description": "Reconciled - has been marked as reconciled in the Vendor Rebate Reconciliation screen", "database": "VARCHAR(3)", "example": "No" },
          "RegionID": { "type": "integer", "description": "Identifier for a region in RQ", "database": "INT", "example": "9" },
          "RegionName": { "type": "string", "description": "Region - region for the rows location", "database": "VARCHAR(100)", "example": "Region B" },
          "RelatedCost": { "type": "decimal", "description": "Related Cost - purchase cost for the product associated with this rebate", "database": "MONEY", "example": "404" },
          "RelatedPrice": { "type": "decimal", "description": "Related Price - price the customer paid for the product related to this rebate", "database": "MONEY", "example": "69.99" },
          "RelatedProduct": { "type": "string", "description": "Related Product - product associated with this rebate", "database": "VARCHAR(100)", "example": "Samsung Galaxy S4" },
          "RelatedProductSerialNumbers": { "type": "string", "description": "Related SN - serial number associated with this rebate, if any", "database": "VARCHAR(1000)", "example": "ACVZCB0026" },
          "RelatedProductSKU": { "type": "string", "description": "Related SKU - product SKU of the product associated with this rebate", "database": "VARCHAR(12)", "example": "ACVZCB000244" },
          "SaleInvoiceID": { "type": "integer", "description": "Internal identifier in RQ", "database": "INT", "example": "126526" },
          "SerialNumber": { "type": "string", "description": "Tracking # - tracking number associated with this entry", "database": "VARCHAR(100)", "example": "123000000000000" },
          "SocCode": { "type": "string", "description": "SOC Code - SOC Code if one was used", "database": "VARCHAR(50)", "example": "123000000000000" },
          "SocCode2": { "type": "string", "description": "SOC Code2 - Second SOC Code if used", "database": "VARCHAR(50)", "example": "" },
          "SpecialIdentifier": { "type": "string", "description": "Sales Person ID - ID number assigned to this sales person and recorded on the Admin tab of their Employee Profile", "database": "VARCHAR(25)", "example": "1" },
          "SpecialIdentifier1": { "type": "string", "description": "Internal identifier in RQ", "database": "VARCHAR (25)", "example": "" },
          "TermCode": { "type": "string", "description": "Term Code - [may not show in your database] indicates new activation, upgrade, etc.", "database": "VARCHAR(200)", "example": "" },
          "TotalPrice": { "type": "decimal", "description": "Total Rebate - total value of the rebate on this invoice calculated as Qty X Unit Rebate", "database": "MONEY", "example": "0" },
          "UnitPrice": { "type": "decimal", "description": "Unit Rebate - dollar value of this rebate", "database": "MONEY", "example": "0" },
          "VendorAccountName": { "type": "string", "description": "Vendor Account Name - vendor account for this rebate", "database": "VARCHAR(100)", "example": "Verizon 2" },
          "VendorName": { "type": "string", "description": "Vendor name in RQ", "database": "NVARCHAR(MAX)", "example": "Verizon" },
          "VendorNumber": { "type": "string", "description": "Vendor # - vendor account number entered for Vendor # By Location [if used]", "database": "NVARCHAR(3)", "example": "" },
          "VendorSKU": { "type": "string", "description": "Vendor SKU", "database": "VARCHAR(25)", "example": "" }                    
        }
      }        
  - Relationship: |
      {
        "name": "Relationship",
        "type": "array",
        "$schema": "http://json-schema.org/draft-03/schema",
        "properties": {
          "CompanyID": {  "type": "integer", "database": "INTEGER", "description": "Identifier for a {{Company}}", "example": "21090" },
          "CompanyName": {  "type": "string", "database": "VARCHAR(50)", "description": "Company name", "example": "KENTEL" }
        }
      }
/partner/relationships?Auth={Auth}&Response={Response}: 
  uriParameters:
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: Relationship
  get:
    displayName: Getting Partner Relationships
/partner/StatFlo/ActivationGrossProfitReport?CompanyId={CompanyId}&StartDate={StartDate}&StopDate={StopDate}&StoreType={StoreType}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&ReasonCode={ReasonCode}&LanguageCode={LanguageCode}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true        
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin
      required: true
    StopDate:
      type: string
      example: 2016-01-01 00:00:00
      description: Date at which report will end
      required: true     
    ReasonCode:
      displayName: ReasonCode
      type: integer
      example: -1
      required: true
      description: Identifier for a <a href='http://developers.iqmetrix.com/api/RQ-Data-Connect/#reasoncode'>ReasonCode</a>. Use -1 to specify All Reason Codes. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-reason-codes">Getting Reason Codes</a>
    StoreType:
      type: integer
      example: -1
      required: true
      description: Identifier for a <a href='http://developers.iqmetrix.com/api/RQ-Data-Connect/#storetype'>StoreType</a>. Use -1 to specify All Types. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-store-types">Getting Store Types</a>
    ForWho:
      type: integer
      example: 4
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 1
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="/api/RQ-Data-Connect/#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false 
    LanguageCode:
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='/api/RQ-Data-Connect/#getting-language-codes'>Getting Language Codes</a>
      required: false
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly: 
      resource: ActivationGrossProfitReportData
  get:
    displayName: Getting the Activation Gross Profit Report
    description: |
      For more information, see {{support_ActivationGrossProfitReport}}.
/partner/StatFlo/CouponSummaryReport?CompanyId={CompanyId}&StartDate={StartDate}&StopDate={StopDate}&ReportType={ReportType}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&LanguageCode={LanguageCode}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true    
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin
      required: true
    StopDate:
      type: string
      example: 2016-01-01 00:00:00
      description: Date at which report will end
      required: true  
    ReportType:
      type: string
      example: DailySummary
      required: true
      description: Acceptable values include DailySummary, LocationSummary, CouponSummary, CouponDetail, EmployeeSummary and CommissionDetail
    ForWho:
      type: integer
      example: 4
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 1
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="/api/RQ-Data-Connect/#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="/api/RQ-Data-Connect/#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false        
    LanguageCode:
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='/api/RQ-Data-Connect/#getting-language-codes'>Getting Language Codes</a>
      required: false
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false            
  type:
    collectionReadOnly: 
      resource: CouponSummaryReportData
  get:
    displayName: Getting the Coupon Summary Report
    description: |
      For more information, see {{support_CouponSummaryReport}}.
/partner/StatFlo/CustomerListReport?CompanyId={CompanyId}&StartDate={StartDate}&StopDate={StopDate}&TypeOfCustomer={TypeOfCustomer}&FilterBy={FilterBy}&StoreIDLoggedIn={StoreIDLoggedIn}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin
      required: true
    StopDate:
      type: string
      example: 2016-06-06 00:00:00
      description: Date at which report will end
      required: true
    TypeOfCustomer:
      type: integer
      example: -1
      description: Acceptable values include -1 for all types, 1 for Company, 2 for Division, 3 for Group and 4 for Individual
      required: true
    FilterBy:
      type: integer
      example: 1
      description: Acceptable values include 0 for All Customers, 1 for First Activation and 2 for Sales
      required: true
    StoreIDLoggedIn:
      type: integer
      example: 1
      description: Identifier for a store in RQ. For a complete list, see <a href='#getting-a-list-of-stores-in-rq'>Getting A List of Stores in RQ</a>
      required: true
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false      
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: CustomerListReportData
  get:
    displayName: Getting the Customer List Report for a Company
    description: |
      For more information, see {{support_CustomerListReport}}.   
/partner/StatFlo/EmployeeMasterListReport?CompanyId={CompanyId}&EnabledStatus={EnabledStatus}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    EnabledStatus:
      type: integer
      example: 1
      description: Select employees with a status of Disabled (0), Enabled (1) or Any Status (2)
      required: true 
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false 
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      

  type:
    collectionReadOnly:
      resource: EmployeeMasterListReportData
  get:
    displayName: Getting the Employee Master List Report
    description: |
      For more information, see {{support_EmployeeMasterListReport}}.   
/partner/StatFlo/GraphedPerformanceMetricsReport_PerformanceMetrix?CompanyId={CompanyId}&PeriodID={PeriodID}&StartDate={StartDate}&StopDate={StopDate}&HideRebates={HideRebates}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&LanguageCode={LanguageCode}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    PeriodID:
      type: integer
      example: 1
      description: Identifier for a Period in RQ, or -1 if a StartDate and StopDate will be used
      required: true
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin. If PeriodID is -1, this value will be ignored
      required: true
    StopDate:
      type: string
      example: 2016-06-06 00:00:00
      description: Date at which report will end. If PeriodID is -1, this value will be ignored
      required: true
    HideRebates:
      type: integer
      example: -1
      description: A flag to indicate if Rebates should be included in the report (1) or not (-1)
      required: true
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false 
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false
    LanguageCode: 
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='#getting-language-codes'>Getting Language Codes</a> 
      required: false
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: GraphedPerformanceMetrixReportData
  get:
    displayName: Getting the Graphed Performance Metrix Report
    description: |
      For more information, see {{support_GraphedPerformanceMetrixReport}}.
/partner/StatFlo/GraphedPerformanceMetricsReport_Breakdown?CompanyId={CompanyId}&PeriodID={PeriodID}&StartDate={StartDate}&StopDate={StopDate}&HideRebates={HideRebates}&PerformanceGroupID={PerformanceGroupID}&TopN={TopN}&TopCriteria={TopCriteria}&ByWho={ByWho}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&LanguageCode={LanguageCode}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    PeriodID:
      type: integer
      example: 1
      description: Identifier for a Period in RQ, or -1 if a StartDate and StopDate will be used
      required: true
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin. If PeriodID is -1, this value will be ignored
      required: true
    StopDate:
      type: string
      example: 2016-06-06 00:00:00
      description: Date at which report will end. If PeriodID is -1, this value will be ignored
      required: true
    HideRebates:
      type: integer
      example: -1
      description: A flag to indicate if Rebates should be included in the report (1) or not (-1)
      required: true
    PerformanceGroupID:
      type: integer
      example: 1
      description: Identifier for a Performance Group in RQ 
      required: true
    TopN:
      type: integer
      example: 10
      description: Gets the top X entries for the report, ordered by the value in TopCriteria. Use -1 to return all results
      required: true
    TopCriteria:
      type: string
      example: Quantity
      description: Acceptable values include Quantity, Sales, Profit, Margin and Rate
      required: true
    ByWho:
      type: integer
      example: 5
      description: This value will aggregate the report data at the Company (1), Region (2), Division (3), Location (4) or Employee (5) level
      required: true
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false 
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false      
    LanguageCode:
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='#getting-language-codes'>Getting Language Codes</a> 
      required: false      
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false        
  type:
    collectionReadOnly:
      resource: GraphedPerformanceMetrixBreakdownReportData  
  get:
    displayName: Getting the Graphed Performance Metrix Breakdown Report
    description: |
      For more information, see {{support_GraphedPerformanceMetrixReport}}.
/partner/StatFlo/LocationMasterListReport?CompanyId={CompanyId}&Auth={Auth}&Response={Response}:   
  uriParameters: 
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false      
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false     
  type:
    collectionReadOnly: 
      resource: LocationMasterListReportData  
  get:
      displayName: Getting the Location Master List Report
      description: |
        For more information, see {{support_LocationMasterListReport}}.   
/partner/StatFlo/ProductDetailReport?CompanyId={CompanyId}&StartDate={StartDate}&StopDate={StopDate}&SearchMethod={SearchMethod}&CategoryNumber={CategoryNumber}&ReportPart={ReportPart}&ManufacturerID={ManufacturerID}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&ProductIdentifier={ProductIdentifier}&InvoiceIDByStore={InvoiceIDByStore}&LanguageCode={LanguageCode}&Auth={Auth}&Response={Response}: 
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin
      required: true
    StopDate:
      type: string
      example: 2016-06-06 00:00:00
      description: Date at which report will end
      required: true
    SearchMethod:
      type: integer
      example: 3
      description: Acceptable values include 1 for Product SKU, 2 for Manufacutrer, 3 for Category and 4 for Invoice Number 
      required: true    
    CategoryNumber:
      type: integer
      example: 10
      description: Identifier for a {{CategoryNumber}}. For a complete list see <a href="#getting-category-numbers">Getting Category Numbers</a>
      required: true
    ReportPart:
      type: integer
      example: 1
      description: Acceptable values include 1 to return the default report, 2 for the tax detail report and 3 for tax column data
      required: true    
    ManufacturerID:
      type: integer
      example: -1
      description: Identifier for a Manufacture in RQ. Use -1 for all Manufacturers. For a complete list see <a href="#getting-a-list-of-manufacturers-in-rq">Getting a List of Manufacturers in RQ</a>
      required: true      
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false 
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false
    ProductIdentifier:
      type: string
      example: ASCLMO000001
      description: Product SKU
      required: false
    InvoiceIDByStore:
      type: string
      example: 77224IN3
      description: Tracking number
      required: false
    LanguageCode: 
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='#getting-language-codes'>Getting Language Codes</a> 
      required: false          
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false      
  type:
    collectionReadOnly:
      resource: ProductDetailReportData
  get:
    displayName: Getting the Product Detail Report for a Company
    description: |
      For more information, see {{support_ProductDetailReport}}.

      Note that this report has multiple responses, depending on the ReportPart specified.

      | Report Part | Response |
      |:------------|:---------|
      | 1 | {{StatFlo-Reports_ProductDetailReportData}} |
      | 2 | {{StatFlo-Reports_ProductDetailReportTaxDetailData}} |
      | 3 | {{StatFlo-Reports_ProductDetailReportTaxColumnData}} |
/partner/StatFlo/VendorRebateHistoryReport?CompanyId={CompanyId}&StartDate={StartDate}&StopDate={StopDate}&SearchMethod={SearchMethod}&ApplyShowOnInvoice={ApplyShowOnInvoice}&ReconciledStatus={ReconciledStatus}&EmployeeIDOfReconcilers={EmployeeIDOfReconcilers}&VendorAccountID={VendorAccountID}&CategoryNumber={CategoryNumber}&ForWho={ForWho}&ForWhoIDs={ForWhoIDs}&LocationType={LocationType}&LocationTypeIDs={LocationTypeIDs}&ProductIdentifier={ProductIdentifier}&LanguageCode={LanguageCode}&SerialNumber={SerialNumber}&JournalNumber={JournalNumber}&Auth={Auth}&Response={Response}:
  uriParameters:
    CompanyId:
      type: integer
      example: 21090
      description: Identifier for a {{Company}}, for a list see Getting Partner Relationships
      required: true  
    StartDate:
      type: string
      example: 1970-01-01 00:00:00
      description: Date at which report will begin
      required: true
    StopDate:
      type: string
      example: 2016-06-06 00:00:00
      description: Date at which report will end
      required: true
    SearchMethod:
      type: integer
      example: 4
      description: Acceptable values include 1 for Vendor Account, 2 for Journal Number, 3 for Reconciled By, 4 for Category, 5 for Tracking Number and 6 for Product SKU 
      required: true           
    ApplyShowOnInvoice:
      type: integer
      example: 0
      description: This value should always be 0 
      required: true       
    ReconciledStatus:
      type: integer
      example: 2
      description: Acceptable values include 0 for Unreconciled, 1 for Reconciled and 2 for Any
      required: true          
    EmployeeIDOfReconcilers:
      type: integer
      example: -1
      description: Identifier of an employee who reconciled the rebate. Use -1 for all employees
      required: true           
    VendorAccountID:
      type: integer
      example: -1
      description: Identifier of a vendor account. Use -1 for all vendor accounts
      required: true          
    CategoryNumber:
      type: integer
      example: 10
      description: Identifier for a {{CategoryNumber}}. For a complete list see <a href="#getting-category-numbers">Getting Category Numbers</a>
      required: true     
    ForWho:
      type: integer
      example: 1
      description: Identifier for a level at which to perform the report. For a complete list, see <a href="#getting-report-levels-in-rq">Getting Report Levels in RQ</a>. If <strong>LocationType</strong> is provided, this value is ignored
      required: false
    ForWhoIDs:
      type: integer
      example: 6679
      description: A comma seperated list of identifiers to filter the report. For a list of identifiers, see <a href="#getting-nodes-by-location-type">Getting Nodes By Location Type</a>. If <strong>LocationTypeIDs</strong> is provided, this value is ignored. To ignore filtering use -1
      required: false 
    LocationType:
      type: string
      example: Store
      description: A {{LocationType}} to filter the report. For a complete list, see <a href="#getting-location-types">Getting Location Types</a>. If this value is provided, <strong>ForWho</strong> is ignored
      required: false
    LocationTypeIDs:
      type: string
      example: 1,2
      description: A comma seperated list of {{RQCompanyTreeNode}} identifiers to filter the report. For a complete list, see <a href="#getting-location-ids">Getting Location Ids</a>. To ignore filtering, use -1 or *. If this value is provided, <strong>ForWhoIDs</strong> is ignored
      required: false      
    LanguageCode: 
      type: string
      example: en-us
      description: Language code, defaults to en-us. For a complete list, see <a href='#getting-language-codes'>Getting Language Codes</a> 
      required: false
    ProductIdentifier:
      type: string
      example: ASCLMO000001
      description: Product SKU
      required: false            
    SerialNumber:
      type: string
      example: 990003427999221
      description: Serial Number
      required: false
    JournalNumber:
      type: string
      example: Feb 2015 Spiff
      description: Journal number
      required: false
    Auth:
      type: string
      example: vRMt17P8rIBWWbVbLzLWjTNyLfvESgA2yfXhze0WZN7HSIl4slGV866p9dSw
      description: Basic token used for authentication. For other methods of authentication, see {{AuthenticationOptions}}
      required: false
    Response:
      type: string
      example: xml
      description: Default is JSON. For other methods of response, see {{ResponseOptions}}
      required: false            
  type:
    collectionReadOnly:
      resource: VendorRebateHistoryReportData
  get:
    displayName: Getting the Vendor Rebate History Report for a Company
    description: |
      For more information, see {{support_VendorRebateHistoryReport}}.    